export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-slate-900 text-white">
      <div
        className="
          flex flex-col
          items-center
          justify-center
          w-3/4	        
          flex-1
          text-center
        ">
        <h1
          className="
          text-5xl
          pb-16
        ">
          Generador de Persoajes
        </h1>
        <textarea
          className="
            w-full
            min-h-[75px]
            max-h-[400px]
            p-5
            bg-slate-800
            text-white
            rounded-md 
            resize-y	
            overflow-y-none
            scrollbar-hide
           "
        />
        <div
          className="
            pt-5
            w-full
            flex
            justify-between
            items-center">
          <div
            className="
              flex
              flex-col
              items-center
              w-1/4
              gap-2
            ">
            <button
              className="
                bg-white
                text-slate-900
                w-full
                h-10
                rounded-md
                hover:bg-slate-900
                hover:text-white
                border-2
                border-white
                ">
              Generador 1
            </button>

            <div
              className="
                w-full
                h-40
                bg-slate-800
                rounded-lg
                border-2
                "></div>
          </div>

          <div
            className="
              flex
              flex-col
              items-center
              w-1/4
              gap-2
            ">
            <button
              className="
                bg-white
                text-slate-900
                w-full
                h-10
                rounded-md
                hover:bg-slate-900
                hover:text-white
                border-2
                border-white
                ">
              Generador 1
            </button>

            <div
              className="
                w-full
                h-40
                bg-slate-800
                rounded-lg
                border-2
                "></div>
          </div>
        </div>
        <button
          className="
                mt-5
                bg-white
                text-slate-900
                w-full
                h-10
                rounded-md
                hover:bg-slate-900
                hover:text-white
                border-2
                border-white
                ">
          Generador
        </button>
      </div>
    </div>
  );
}
